### ISSUE TITLE
Suggestion - search for seeds that have a potion, item or spell in a level

### ISSUE THREAD

**Issue by theo543** [TwoAbove/noita-tools#100]
As in, being able to select a list of things that you want to find in a level (probably the mines), i.e. if you wanted to search for orbs you could search for a seed that has, in the mines, the ingredients for guiding powder and a wand with digging spells. Or search for a seed with a fire stone to evaporate the water in the dark cave, etc. After finding the seed it could show you a list of items per level so you know if there is some rare item in a level.

Also, thanks for making this tool!

**Comment by TwoAbove** [comment]
Linking this to #102 – is a prerequisite to this
