### ISSUE TITLE
Second Shift Incorrect?

### ISSUE THREAD

**Issue by ManaUser** [TwoAbove/noita-tools#103]
So I'm playing 1167871042 and the first shift worked as expected **Oil,Swamp,Peat** to **Poison/Flask** (used a flask). But on the second shift weird fungus turned to blood (bummer). What the tool predicted was  **Freezing Liquid,Worm Blood** to **Fungus Blood**. So it almost seems like this was reversed or something? I had a pouch of weird fungus but not in my hands, in case that's relevant.

**Comment by TwoAbove** [comment]
Thanks for letting me know! I'll check to see if there has been a regression

**Comment by TwoAbove** [comment]
@ManaUser You're right, there was a regression that happened when I split up all the files. Should be fixed once deploy completes:
https://github.com/TwoAbove/noita-tools/pull/105
