### ISSUE TITLE
Simple as that: Put default values in the text inputfields?

### ISSUE THREAD

**Issue by Ismoh** [TwoAbove/noita-tools#104]
Just saw your mod in the modding-showcase channel and wanted to have a quick look, but I am too lazy to type anyhting in.
Maybe you just want to add some default values to get a really quick look on this?!

**Comment by TwoAbove** [comment]
Hey! Not sure what you mean by this.

Add default values in the tool somewhere, or default values in these issues?

**Comment by Ismoh** [comment]
Yea sorry!
I mean the webpage. So a default seed. In addition to this the seed and beta live tracker was loading without any end. After 5min I closed it.

**Comment by TwoAbove** [comment]
That's interesting :thinking: 

Everything loads for me without issue. Can you share what you're using to access the site? OS and browser version ideally.

Moreover, I don't see the need to provide a default seed because it seems counterintuitive to see useless information for your specific game, and it's 1 input away from getting relevant info from the tool.

**Comment by TwoAbove** [comment]
Okay, I can replicate this issue. I'll see what's the issue

**Comment by TwoAbove** [comment]
@Ismoh If you are using Firefox, then I can see that for some reason a library that's needed to get OCR running

**Comment by TwoAbove** [comment]
Hey @Ismoh I found the issue, should be deployed in ~15 mins

**Comment by Ismoh** [comment]
> That's interesting :thinking: 
> 
> Everything loads for me without issue. Can you share what you're using to access the site? OS and browser version ideally.
> 
> Moreover, I don't see the need to provide a default seed because it seems counterintuitive to see useless information for your specific game, and it's 1 input away from getting relevant info from the tool.

Yea sure, as you prefer!
I used chrome, but adblock and ghostery extension. Maybe this might be a problem.
