### ISSUE TITLE
BUG - Live Game Helper doesn't load new seed

### ISSUE THREAD

**Issue by Hirashi3630** [TwoAbove/noita-tools#118]
## Describe the bug
Live Game Helper does not try to load new seed
it loads the first seed right after enabling screen capture just fine

## To Reproduce
Start screen capture
wait for it to load first seed
load a new seed
nothing happens

## Expected behavior
should try to read the new seed 

I'm not sure if I'm doing it right or it's not yet implemented because of beta

maybe a shortcut/button to manually refresh it would be nice

**Comment by TwoAbove** [comment]
Hey! A good idea to have a refresh button – It should be deployed at the beginning of next week!

**Comment by TwoAbove** [comment]
Ideally, you should just get updates and that's it, but I agree that it's flaky

**Comment by Hirashi3630** [comment]
Maybe global shortcut would be even better but I'm not sure if that's even possible with websites

**Comment by TwoAbove** [comment]
@Hirashi3630 Added a force-restart button for OCR

It will be deployed once this PR turns green
https://github.com/TwoAbove/noita-tools/pull/127

**Comment by Hirashi3630** [comment]
@TwoAbove tested the feature and it does not seem to work

pressing the button doesn't do anything

using v2.10.1

**Comment by TwoAbove** [comment]
@Hirashi3630 
Can you tell me what browser/os combo you use?
Thanks

**Comment by Hirashi3630** [comment]
Google Chrome Version 98.0.4758.102 (Official Build) (64-bit)
Windows 10
