### ISSUE TITLE
BUG - [Search by Alchemy not returning results]

### ISSUE THREAD

**Issue by CalebRenshaw** [TwoAbove/noita-tools#119]
## Describe the bug
 When attempting to search for seeds by parameters of alchemy ingredients, results will not return, regardless of seed start or end point (if included), Multithreading setting, or ingredient selection. The status of a search will display, but will not return results, even after search finishes. 

## To Reproduce
1. Go to 'Search For Seed, Alchemy'
2. Click on 'Any combination of ingredients, Enter any seed range, click Find Next '
3. Scroll down to 'Bottom of Page'
4. See error: No results appear.

## Expected behavior
A search will run from the start seed to (optional) end seed, and will display progress, but will not yield any results for the search, as are returned when searching by other, non-alchemy, parameters.

## Additional context
I'm running on Kubuntu 20.04 Linux with a Ryzen 3700x 8-core cpu.
This behavior occurs on both Mozilla Firefox and Google Chrome.

**Comment by TwoAbove** [comment]
Hello @CalebRenshaw !
Can confirm, I'll deploy a fix shortly

**Comment by TwoAbove** [comment]
@CalebRenshaw https://github.com/TwoAbove/noita-tools/pull/120 will fix this. Thanks for the bug report!

**Comment by TwoAbove** [comment]
Should be deployed in ~5 minutes

**Comment by TwoAbove** [comment]
@CalebRenshaw I made a regression here, I'll add a fix in the next release which I expect to deploy in the coming few days

**Comment by CalebRenshaw** [comment]
Okay, I'll keep an eye out for it.
Thanks for the tool and the work you do on it.

**Comment by TwoAbove** [comment]
@CalebRenshaw 
It will be deployed once this PR turns green
https://github.com/TwoAbove/noita-tools/pull/127
