### ISSUE TITLE
QoL change - Alchemy tweaks

### ISSUE THREAD

**Issue by CasuallTea** [TwoAbove/noita-tools#122]
Alchemy recipes don't specify if active or non active gunpowder is used, which is important as the active gunpowder can't be used in any alchemy due to not persisting in the world. Also, swamp comes in two flavours - one you get in flasks at the start of game and in pockets in the jungle, and one created along with peat when mixing toxic sludge and mud. I have seen this on seed 1927166435:

![image](https://user-images.githubusercontent.com/100135198/154954232-7c6d6982-a632-4ec6-83a0-66dc5b1df0a1.png)

I don't know what swamp I'd need for the LC here.

Is it possible to specify what materials are the catalysts and what is consumed in the recipes? In alchemy one ingredient is needed in bulk and the other two only need to be sprinkled on.

**Comment by TwoAbove** [comment]
Hey! Yes, it's totally possible to do – I'll add an explanation with the material_name in the next update (maybe Tuesday or Wednesday)

**Comment by TwoAbove** [comment]
@CasuallTea I added a settings page with the option to show IDs
It will be deployed once this PR turns green
https://github.com/TwoAbove/noita-tools/pull/127
