### ISSUE TITLE
UI Arrangement Suggestions

### ISSUE THREAD

**Issue by smb64** [TwoAbove/noita-tools#123]
I think rearranging the Live Seed Data tab might make it easier to use. Having the capture button near the top with a refresh button next to it would be great. Also moving the Alchemy Recipes section below the perks and the biome modifiers below the Alchemy section would help reduce the length of the website by a large margin, since the Fungal Shifts take up nearly twice the space the other three sections do combined.

**Comment by smb64** [comment]
Also having an option to lock in perks (via right-clicking like with cr4xy does for rerolls on their site) would help greatly when using perk lottery.

**Comment by TwoAbove** [comment]
Hey! Thanks for the suggestion

**Comment by TwoAbove** [comment]
Thank you

**Comment by TwoAbove** [comment]
@smb64 Added a button to force-restart the OCR
