### ISSUE TITLE
Suggestion - always cast support

### ISSUE THREAD

**Issue by givensnickel** [TwoAbove/noita-tools#124]
I have no idea what the dependencies are to determining what the spell given by always cast is, but if it could be reported from the world info already gathered that would be amazing.

**Comment by TwoAbove** [comment]
Hey @givensnickel 
I'm still working on the wand info - the spells are not accurate for some reason, so I'm not showing them at this time

**Comment by TwoAbove** [comment]
@givensnickel This is live from v2.18
