### ISSUE TITLE
Suggestion - Ideas for ease of use on random seeds

### ISSUE THREAD

**Issue by CasuallTea** [TwoAbove/noita-tools#125]
I use the tool by loading a new game, typing in the seed and seeing if there are any interesting alchemy, perks, or shifts to be had early. For perks, this requires me to check the first 3-4 rerolls to see if perks I like show up, and sometimes to check parallel worlds. 

Is it possible to pre select a perk or perks, and a UI element tells me where I can find it? e.g I choose perk lottery and tinker everywhere. I type in the seed I'm using, and the site highlights the tinker perk being in the fourth HM and lottery is just 2 rerolls away. Maybe a small icon next to the reroll up, or just highlighting it green, or a separate box noting where it is.

This could expanded to alchemy and shifts, by selecting materials. I like seeds where poly, lava and acid can be shifted, or where water is an alchemical ingredient (and not something like urine)

Additionally, when typing in a new seed, can the rerolls, perk lottery picks and extra perk picks be automatically reset? I can't see why a user would want to keep the fact they'd rerolled four times, or picked up extra perks in a previous run, when using a new seed.

Finally, the input box for the seed has the option for minus numbers which seems to break the site, and also has up and down arrows to increment the number which I'm not sure is needed!

**Comment by TwoAbove** [comment]
Hey @CasuallTea!

Thanks for the suggestions - I have the "favourite" feature planned, but there are a few things that I need to do first before I implement it.

As for the perk state and input box, that's a bug and I'll fix it in my next release. 

Thanks!

**Comment by TwoAbove** [comment]
I'll leave this as a feature request

**Comment by TwoAbove** [comment]
@CasuallTea https://github.com/TwoAbove/noita-tools/pull/183 adds the `Favorites` config in settings. Supports perks, spells, and materials.
