### ISSUE TITLE
BUG and Suggestion- [Reduce Reroll button disappeard?]

### ISSUE THREAD

**Issue by hyunki** [TwoAbove/noita-tools#128]
![image](https://user-images.githubusercontent.com/25163778/155473072-c19b4b2b-f23a-47bd-bfe6-a30377b49d6d.png)
There was a reroll back button but it is disappeard now.

browser
chrome 98.0.4758.102(official build) (64bit)

[Suggestion]
I hope there is url post-get method.
When I submit the seed, url query or path show the seed so I can bookmark or search from web history.
like this
https://noita-tools.herokuapp.com/seed?=1280001652
or
https://noita-tools.herokuapp.com/1280001652

**Comment by smb64** [comment]
same here, seems like the buttons got removed by mistake or the new layout moved them off the page.
Also the OCR still does not seem to recapture the Seed when loading a new game nor does the Reset Stuck OCR button seem to work.

**Comment by TwoAbove** [comment]
@hyunki @smb64 Soory, my mistake

**Comment by TwoAbove** [comment]
Should be deployed
