### ISSUE TITLE
Browser (Chrome) hanging after using Advanced Mode

### ISSUE THREAD

**Issue by smb64** [TwoAbove/noita-tools#137]
I activated advanced mode in the Live Seed Data tab, then clicked [load] for the second HM. The page immediately went blank except for the background color. After reloading the page, I tried to capture the game and the browser stopped responding. I had to end the process and restart Chrome.

**Comment by TwoAbove** [comment]
Hey! any info on the seed or more info?

**Comment by TwoAbove** [comment]
Hm, will try to reproduce

**Comment by TwoAbove** [comment]
Okay! I'll get a fix out asap

**Comment by TwoAbove** [comment]
@smb64 https://github.com/TwoAbove/noita-tools/pull/138 should fix this. Thank you for the report!
