### ISSUE TITLE
Save to accout/file

### ISSUE THREAD

**Issue by davidaffo** [TwoAbove/noita-tools#139]
I would like to open the site and have the perk that I have selected saved as well as the rerolls. So if I close my PC and re-open noitool I don't have to insert manually everything. This might be done either by saving data on the server or even downloading a file that we can re-upload with the information needed to get back the state of noitool when we closed it.

**Comment by TwoAbove** [comment]
Hey! 
This will have to wait until I think of a good way of doing https://github.com/TwoAbove/noita-tools/issues/125. After that's done, this will be a freebie. 
I plan on starting #125 after I'm done disassembling the level generation code for #100 and #102

**Comment by FlauschigerPara** [comment]
@TwoAbove 
I just signed up to Github to write here :-)
I would also prefer some kind of save-feature but i think it might be easier to just make a copy&paste-able string which changes with every change i made on the website.
Like <seednumber>&reroll1&perk2.

Usually i write down the current seed in a seperate text file after i start a new run and write the two alchemy reciepes.
So it would not be a problem to just copy the current status-string aswell in the file.

This might be less complex as a file-operation to save and load a file just for this feature.

**Comment by TwoAbove** [comment]
@FlauschigerPara sounds great!

After I finish with the two bugs, I'll start working on saving

**Comment by TwoAbove** [comment]
@davidaffo @FlauschigerPara Now seed state is persistent through refreshes
