### ISSUE TITLE
BUG - Perk availability doesn't update

### ISSUE THREAD

**Issue by samuelepozzebon** [TwoAbove/noita-tools#141]
## Describe the bug
Perk availability in the following Holy Mountains does't update if you get "Extra Perk" with a "Gamble".

## To Reproduce
You can observe this behaviour in the seed 933195064, both with and without the "Advanced" mode:
1. Load the seed 933195064
2. Reroll the first Holy Mountain to get the Gamble perk
3. Select it

## Expected behavior
Every following Holy Mountain should now have 4 perks each. Instead there have only 3.

## Screenshots
![image](https://user-images.githubusercontent.com/72387285/159372170-ad976f31-97d2-4745-9e44-65cc3f587398.png)

**Comment by TwoAbove** [comment]
Thanks! Can confirm the bug, I'll get a fix out in the next few days

**Comment by TwoAbove** [comment]
@samuelepozzebon Bugfix is in develop. I'll test and it should be up in a couple of hours
