### ISSUE TITLE
BUG - Several Search Parameters Not Working

### ISSUE THREAD

**Issue by CalebRenshaw** [TwoAbove/noita-tools#147]
## Describe the bug
Alchemy, Starting Flask, and the Fungal Shift "To" and "From" fields all stall on a blank, unresponsive page rendering the tools nonfunctional.

## To Reproduce
1. Go to "Search for Seed"
2. Click on "Alchemy", "Starting Flask", or "Fungal Shifts".
3. Scroll down to (you can't; page becomes unresponsive)

## Expected behavior
The page will be blank and unresponsive

**Comment by TwoAbove** [comment]
Thanks! I'll get a fix out ASAP

**Comment by TwoAbove** [comment]
@CalebRenshaw Should be fixed
