### ISSUE TITLE
Selected perks not removed from pool in Advanced mode

### ISSUE THREAD

**Issue by EPacifist** [TwoAbove/noita-tools#148]
You can click perks to apply them but it's odd that certain perks aren't removed from the pool e.g. explosion immunity. Really only has a significant effect when collecting perks while going through multiple parallel worlds to break the reroll machine, but I'd expect the "advanced" mode to be that advanced.

**Comment by TwoAbove** [comment]
Hey! Thanks for the info, I'll double check the generating code, looks like a bug

**Comment by TwoAbove** [comment]
@EPacifist You're right, I didn't transfer the noita lua correctly. Thanks!
