### ISSUE TITLE
Incorrect spells in holy mountain

### ISSUE THREAD

**Issue by big-smitty** [TwoAbove/noita-tools#153]
## Describe the bug
Items in holy mountain spell shops do not match expected spells

## To Reproduce
1. Have all spells unlocked
2. Enter a new seed, check expected spells, go to shop
3. They are not the same (but they are similar)

## Expected behavior
They should be the same

## Screenshots
On Seed 1611006573
![image](https://user-images.githubusercontent.com/85451361/162635588-ab494659-ab7d-4384-ab35-53d457af61e9.png)
![image](https://user-images.githubusercontent.com/85451361/162635616-799183c5-dee2-48ab-89c8-9fafda5b1cef.png)
![image](https://user-images.githubusercontent.com/85451361/162635608-ea8979e1-02bc-42dc-aef1-40389888bf62.png)

## Additional context
running at noitool.com
latest version of noita

**Comment by TwoAbove** [comment]
Hey! 

Can you confirm that you unlocked all spells in the game?

**Comment by TwoAbove** [comment]
Okay, I'll see what I can do.

**Comment by TwoAbove** [comment]
@big-smitty Found the bug. A fix will be out shortly

**Comment by big-smitty** [comment]
Sure,
I _should_ have all spells unlocked. But I didn't unlock Giga-nuke and Giga-Holy Bomb by doing the Friend quest, I just debugged in the spell and cast it to add it to the progress menu. Would that interfere?
Otherwise I do have full progress, see clip below.
![image](https://user-images.githubusercontent.com/85451361/162648179-a4541f88-3ff0-4d12-8dd6-ef4f26812756.png)

**Comment by TwoAbove** [comment]
Thank you for the report!

**Comment by TwoAbove** [comment]
@big-smitty the fix should be deployed!
