### ISSUE TITLE
Incompatible spells in shop

### ISSUE THREAD

**Issue by big-smitty** [TwoAbove/noita-tools#156]
## Describe the bug
level 3 shop spells list includes some spells which aren't available in that shop.

## To Reproduce
See photo. 'Touch of' spells aren't available in the level 3 shop.

## Expected behavior
Only items in shop that are supposed to be available

## Screenshots
![image](https://user-images.githubusercontent.com/85451361/163070234-68d23d41-f255-4937-a3be-fdd4ec333101.png)

**Comment by TwoAbove** [comment]
From the code it seems that they are :thinking: I'll look into how Noita does it again

**Comment by big-smitty** [comment]
I suppose I could be wrong, but thats been my experience when modding some spell mods. I am checking by running the seed checker for touch of spells, I haven't found a seed in the first 15 million that has touch of gold or touch of water. I'm checking the others next

**Comment by TwoAbove** [comment]
@big-smitty You're right! There's a bug in how I generated the spawn_probabilities - there were stray 0s that this list did not filter out. So both of your bugs will be fixed either today or tomorrow morning

**Comment by TwoAbove** [comment]
@big-smitty  Should be deployed shortly
