### ISSUE TITLE
Not an issue but an idea

### ISSUE THREAD

**Issue by HentaiGIFs** [TwoAbove/noita-tools#16]
First of, the seed finder tool is amazing and I want to say thank you for posting it, you rock.

I just had an idea while I was searching for seeds, what if the program somehow put all the results into a database that people could search through instead of having to wait for the program to check each one sequentially? I understand there's like 4 billion possible seeds so maybe it's not even possible, but it would be amazing if we were able to get results instantly when we're looking for really specific seeds.

**Comment by HentaiGIFs** [comment]
also I just realized I could have posted this in discussions, sorry about that! New to github

**Comment by TwoAbove** [comment]
Hey! Interesting idea! 

It won't be that hard to add this type of caching, so I'll think of how to do it.

**Comment by TwoAbove** [comment]
@HentaiGIFs  

Can you elaborate a bit about how you see yourself using this feature? I'd love a bit more information! 

Like a "popular seeds" list? 
Or after selecting a specific set of ingredients, it will show a list of all seeds that has that combination? 

Please share your thought

**Comment by HentaiGIFs** [comment]
Oh a popular seeds thing would be cool as well!

But yeah I was originally picturing being able to select the ingredients you want like normal, but it shows all the results using some kind of database. Basically the program would run through all possible seeds once, save the results, and then allow people to filter through that instead of having to run the program for each search.

I hope I worded that in a way that makes sense.

At the moment I've just been opening a few tabs of the tool and searching for the same recipe from different starting points, but it takes a while when you search for something specific :p

Thanks for the reply and thanks again for all the work you put into this tool!

**Comment by TwoAbove** [comment]
Hm, an instant list in an interesting idea. If the output db is less than a few GiB, then it's doable without much money. 
I'll investigate in my free time and see what is possible.

**Comment by HentaiGIFs** [comment]
Awesome, hopefully there's some way to do it!

I don't know very much about coding but I did some math today and since there's about 4 billion seeds (I think), even if each recipe result was somehow a byte it would be like 4 gigabytes just for that, if I did the math right. 
Maybe there's some way to represent each material in acsii or each recipe in Unicode or something to save on space,  but I'm not sure. My roommate guessed it would probably take like 8 bytes per seed realistically, which would be like 40 to 50 gigabytes, and I know servers can get spendy. 

Whether it ends up being feasible or not, I still appreciate you taking the time to consider it and reply. If you end up coming up with any ideas I look forward to seeing them! 

Thanks again!

**Comment by TwoAbove** [comment]
Hey @HentaiGIFs 
I couldn't think of a good way to make this happen. Now, the tool supports multithreading, so it should be easier to search for seeds. I do want to enhance the tool to have more bells and whistles like cr4xy's does, but this is a bit overkill for a hobby project
