### ISSUE TITLE
[BUG] Seed doen't update - Live game helper

### ISSUE THREAD

**Issue by Knopfi02** [TwoAbove/noita-tools#160]
When using the Live game helper I have noticed, that the seed doesn't update when starting a new run in Noita.

It happens all the time and nothing seems to fix it
I´m using it on the newest version of Opera GX  (LVL 3 core: 85.0.4341.72)

**Comment by Knopfi02** [comment]
By the way, if i restart the screen capture it just gets stuck on the new seed

**Comment by TwoAbove** [comment]
Hey @Knopfi02! Thanks for opening this ticket. It's a semi-known problem, and I'm still digging into as to why it's happening. 
Does it show just one seed and then stops working? Or does it work for some time and then stops?

**Comment by TwoAbove** [comment]
Linking this as it's not fixed 
https://github.com/TwoAbove/noita-tools/issues/118

**Comment by Knopfi02** [comment]
@TwoAbove It works for exactly one seed and then stops.

A few minutes ago I was experimenting around with it and I got a seed, which seemed to confuse the OCR.
The number was shorter than the actual seed and when reloading the website I got the same number,
After trying to screen cap Noita (instead of the entire screen) it got the actual seed (however it was also cut off somewhere in the middle)
Sadly I didn't think of screenshotting the seed

**Comment by Knopfi02** [comment]
I forgot about the seed history!
The actual seed is 1670479003  (I also typed it in manually)

When capturing the entire screen I got 56704
and capturing Noita itself got me  67047

**Comment by TwoAbove** [comment]
Aha, thanks. I'll take a look

**Comment by Knopfi02** [comment]
a few minutes ago I tried the weird seed again 
(right now it doesn't recognize anything)

capturing the entire screen:
- 1670

capturing Noita:      (I got all of these multiple times in a row)
- 167047
- 56
- the actual seed

I hope this helps!

**Comment by Knopfi02** [comment]
Found another cursed seed: 1307447430

**Comment by Knopfi02** [comment]
I'll just list them here and update when I find a new one:
1670479003
1987766134
1307447430
415018113
1755846908

**Comment by TwoAbove** [comment]
Thanks! This one is proving difficult to pin down. It might take some time. In the mean time, I found that hovering your cursor next to the seed number text helps!

**Comment by TwoAbove** [comment]
@Knopfi02 the OCR should be better now

**Comment by TwoAbove** [comment]
I'll keep looking into the other issue about the OCR randomly stopping working, though!
