### ISSUE TITLE
Suggestion - Get seed number by print

### ISSUE THREAD

**Issue by denis-rossati** [TwoAbove/noita-tools#166]
Typing the seed number sucks.

I'm a weak noita player, I click "new game" and enter the seed in the browser, if the desired perks or wands aren't there, I start a new world. I'm sure that I'm not the only one who does this. With that said, not typing the seed would be a good enhancement and a cool time saver. Besides the huge improvement in the UX.

For me, the ideal experience would be: I start a new game, push `ESC` and print entire the screen. In noitool website I have a field where I can load my image (or just `CTRL + V` it) and the system should be able to get the seed by its own. 

I don't know how hard it would be to implement this but it would be great :D What do you guys think, am I dreaming too much or it's a good challenge?

**Comment by TwoAbove** [comment]
@denis-rossati Look at using the Live Game helper (third tab) - that's exactly what you're looking for

**Comment by denis-rossati** [comment]
I've tried to use it, but the screen record feat has a trade off: some users doesn't have a good PC so the feat can slow down their games a lot (hapenned to me) and some of them can be unconfortable and/or suspicious about sharing their screens during the game. Writing this comment I thought "they can just start recording their screen and then stop recording after the app get the seed" but this would not be as quick as taking the screenshot and sending to analisys, not to mention that it wouldn't have the trade off above

**Comment by TwoAbove** [comment]
Hm, I'll think of a way to use the same system for this. I'll reopen this as a feature request

**Comment by TwoAbove** [comment]
@denis-rossati In the live seed stats tab, you can now paste screenshots from buffer
