### ISSUE TITLE
BUG - selecting a seed history results in a white page and a error in the console.

### ISSUE THREAD

**Issue by denis-rossati** [TwoAbove/noita-tools#167]
## Description
The seed history function works for half a second but then it turns into a totally white page and a error in the console.

## To Reproduce

![5d77e448-3ec3-4a9c-9df7-3188b8161e30](https://user-images.githubusercontent.com/74881282/164952577-f2b5081b-7994-4a69-8595-8593ca7f32c2.gif)

- I entered the website and inserted a seed.
- Later on, I returned to the site and clicked "Seed History".
- When I click in any seed, the background seems to load the seed info, but immediately the page goes blank and a error in the console appears: 

![Screenshot from 2022-04-23 22-49-59](https://user-images.githubusercontent.com/74881282/164952301-06a6bad4-ddd7-4e02-8785-64ba0aa0d231.png)

## Additional question

If the functionality works for y'all but not for me, there is a chance that only certain numbers throw an error? O.o

**Comment by TwoAbove** [comment]
Hey! I can't seem to reproduce this issue. Does this persist when you clear the DB in settings?

**Comment by TwoAbove** [comment]
Also, what is the seed number that doesn't work?

**Comment by denis-rossati** [comment]
Hi, the seed that doesn't worked is `328361950`.

I can't reproduce either :P after I posted the issue I reseted through the configuration tool and I started to work, but I'll give a couple more tries later
