### ISSUE TITLE
BUG - Translation is mixed, Perk lottery with gamble.

### ISSUE THREAD

**Issue by hyunki** [TwoAbove/noita-tools#168]
Hi,

Some perk information display japanese, chinese, swedish in Korean site.

below is the what I found.
others seems ok.

![image](https://user-images.githubusercontent.com/25163778/164992169-596a3b3b-e3a1-4200-aa26-bd1520a3b5de.png)
![image](https://user-images.githubusercontent.com/25163778/164992181-49f1d75b-5b8b-4ec2-8179-aa456c691ec3.png)
![image](https://user-images.githubusercontent.com/25163778/164992213-d024bed4-5cb9-4d47-aa80-9cb163eaf1de.png)
![image](https://user-images.githubusercontent.com/25163778/164992222-f55e20d4-52ab-46a7-9a3c-252ecbd3b067.png)

**Comment by hyunki** [comment]
![image](https://user-images.githubusercontent.com/25163778/164992376-59a05534-f3cc-49b3-857c-9edfe4361f93.png)
When acquire perk lottery with gamble, site doesn't display lottery icon.

**Comment by TwoAbove** [comment]
Thank you! I'll check it out

**Comment by TwoAbove** [comment]
You won't believe it, but some translations in the korean variant are in other languages! I'll check noita's translation files just to be sure

**Comment by TwoAbove** [comment]
@hyunki The translation strings should now all be Korean, but, unfortunately, I cannot fix the translation correctness – I don't know Korean. I took these translations from Noita itself, so if the translations are incorrect, then they would be incorrect in the game too. 

If you have the time and would like to fix this, then you can edit https://github.com/TwoAbove/noita-tools/blob/develop/public/locales/ko/materials.json with correct translations
