### ISSUE TITLE
BUG - Entire website crashing on certain input

### ISSUE THREAD

**Issue by big-smitty** [TwoAbove/noita-tools#169]
## Describe the bug
I'm not sure what exactly is causing the bug, but I can reproduce it on Chrome, Edge, and Tor.
The entire website goes white and then the tab closes after a certain input

## To Reproduce
1. Enter seed '975858680'
2.  Click 'advanced'
3. get to second holy mountain, click the perk lottery
4. click to roll the shop
5. the whole site crashes

## Additional context
After crashing the site wont load again.

**Comment by TwoAbove** [comment]
Thanks! Will look into it ASAP

**Comment by TwoAbove** [comment]
I can't reproduce on local :thinking: 

Is there anything in the console when it crashes? (press F12)

**Comment by M7mdKady14** [comment]
I seem to have the same problem
in the console it showed two nearly identical errors, here is one of them

`index.tsx:16 v2.14.1
/locales/en-US/materials.json:1          Failed to load resource: the server responded with a status of 404 (Not Found)
/locales/en-US/app.json:1          Failed to load resource: the server responded with a status of 404 (Not Found)
react-dom.production.min.js:186 TypeError: Cannot read properties of undefined (reading 'id')
    at HolyMountain.tsx:171:46
    at Array.map (<anonymous>)
    at J (HolyMountain.tsx:169:16)
    at yo (react-dom.production.min.js:166:137)
    at _s (react-dom.production.min.js:214:217)
    at fl (react-dom.production.min.js:291:202)
    at su (react-dom.production.min.js:279:379)
    at au (react-dom.production.min.js:279:310)
    at iu (react-dom.production.min.js:279:170)
    at Kl (react-dom.production.min.js:270:443)
ns @ react-dom.production.min.js:186
n.callback @ react-dom.production.min.js:186
aa @ react-dom.production.min.js:137
ll @ react-dom.production.min.js:261
sl @ react-dom.production.min.js:259
ol @ react-dom.production.min.js:258
(anonymous) @ react-dom.production.min.js:282
uu @ react-dom.production.min.js:280
Yl @ react-dom.production.min.js:272
Li @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
react-dom.production.min.js:127 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at HolyMountain.tsx:171:46
    at Array.map (<anonymous>)
    at J (HolyMountain.tsx:169:16)
    at yo (react-dom.production.min.js:166:137)
    at _s (react-dom.production.min.js:214:217)
    at fl (react-dom.production.min.js:291:202)
    at su (react-dom.production.min.js:279:379)
    at au (react-dom.production.min.js:279:310)
    at iu (react-dom.production.min.js:279:170)
    at Kl (react-dom.production.min.js:270:443)
(anonymous) @ HolyMountain.tsx:171
J @ HolyMountain.tsx:169
yo @ react-dom.production.min.js:166
_s @ react-dom.production.min.js:214
fl @ react-dom.production.min.js:291
su @ react-dom.production.min.js:279
au @ react-dom.production.min.js:279
iu @ react-dom.production.min.js:279
Kl @ react-dom.production.min.js:270
Yl @ react-dom.production.min.js:272
Li @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
`

**Comment by TwoAbove** [comment]
The `locales` parts are intended - that's the translation files

**Comment by TwoAbove** [comment]
I can reproduce finally! I'll push a fix as soon as possible

**Comment by TwoAbove** [comment]
Fix will come out in a few minutes

**Comment by M7mdKady14** [comment]
Thanks a lot!!
your work is much appreciated
