### ISSUE TITLE
Multithreading broken

### ISSUE THREAD

**Issue by Entropy675** [TwoAbove/noita-tools#17]
Multi threading broken lol

For example, it will take longer to find seeds, missing seeds that fit the requirements, and the seeds that it does find are often wrong.

Missing a seed that fits the requirements:
![image](https://user-images.githubusercontent.com/62915307/131288310-97ab9458-f965-40c1-8d5d-6a7ffe5fa674.png)

Cross checking the seed it gives in this example with what the checker says:
![image](https://user-images.githubusercontent.com/62915307/131288433-1be7f283-a4ad-4455-a4dc-2dbe0a7e00b0.png)

**Comment by TwoAbove** [comment]
@Entropy675 Thanks for the bug report. I've reverted the change while I investigate

**Comment by TwoAbove** [comment]
Hey @Entropy675 check the dev branch out: https://noita-tools-dev.herokuapp.com/
should be fixed
