### ISSUE TITLE
BUG - Gamble double extra perk and perk order

### ISSUE THREAD

**Issue by hyunki** [TwoAbove/noita-tools#180]
![20220506 175411-Noitool - Chrome](https://user-images.githubusercontent.com/25163778/167100159-f0493d33-5612-4aa0-9ac1-824e53c8119f.png)
gamble make the 'Extra perk' applied twice when it is on the next deck.
![20220506 175416-Noitool - Chrome](https://user-images.githubusercontent.com/25163778/167100180-f678097d-a2d5-46c7-860c-e59c4b488535.png)

![image](https://user-images.githubusercontent.com/25163778/167100781-5f2f6bb6-dae8-4dcd-91fb-6fa8cf45cd00.png)
This is actual mountain.

+
Perk order in the mountain is diffirent from the site.
![image](https://user-images.githubusercontent.com/25163778/167105874-88de52e9-b4ec-4ca6-9408-f9d93069dbed.png)
![20220506 183011-Noita - Build Apr 23 2021 - 18_44_24](https://user-images.githubusercontent.com/25163778/167106004-6b17e256-64c4-4ee1-bf13-18185229bb88.png)

**Comment by TwoAbove** [comment]
Hm, this is an interesting one. Thanks! I'll make a fix asap

**Comment by TwoAbove** [comment]
Thank you for the seed ❤️

**Comment by TwoAbove** [comment]
@hyunki https://github.com/TwoAbove/noita-tools/pull/181 should fix both issues

**Comment by TwoAbove** [comment]
If anything comes up, create a new issue or re-open this one
