### ISSUE TITLE
BUG - Empty page when submit seed

### ISSUE THREAD

**Issue by hyunki** [TwoAbove/noita-tools#184]
Hi,
noitool.com has a problem.
The site gone white when submit a seed.

https://noita-tools.herokuapp.com/ 
seems fine

**Comment by TwoAbove** [comment]
Hi @hyunki! What seed causes problems?

**Comment by hyunki** [comment]
This is the capture of the problem.


https://user-images.githubusercontent.com/25163778/167630046-b2f341c3-b96f-4f62-99f7-f73d3d401105.mp4

**Comment by TwoAbove** [comment]
Thanks! Can reproduce. Will create a fix asap

**Comment by TwoAbove** [comment]
@hyunki https://github.com/TwoAbove/noita-tools/pull/185 should fix this
