### ISSUE TITLE
BUG - Perk Doesn't match

### ISSUE THREAD

**Issue by hyunki** [TwoAbove/noita-tools#191]
![2022-05-20 01_37_43-Noita - Build Apr 23 2021 - 18_44_24](https://user-images.githubusercontent.com/25163778/169387177-b6ff054a-acf6-42c5-b3bf-7dd53364897f.png)
Perks don't match with site from the third mountain.
I didn't select the gamble perk but in site it has still has a bug i guess.

![2022-05-20 01_37_51-Noitool - Chrome](https://user-images.githubusercontent.com/25163778/169387187-c696dd15-8f55-40b0-8ad1-efdf4eee647a.png)

**Comment by TwoAbove** [comment]
Thanks! I'll get a fix done ASAP

**Comment by TwoAbove** [comment]
Found how to reproduce. I'll have a fix out later today

**Comment by TwoAbove** [comment]
@hyunki I have a fix, will go out with today's feature deploy!
