### ISSUE TITLE
BUG - Javascript error 'undefined' on seed search

### ISSUE THREAD

**Issue by snake0484** [TwoAbove/noita-tools#197]
## Describe the bug
19029210
19802959
23610693
27100281
Cause a js error and do not produce any results.

## To Reproduce
Goto either site to the Seed info page, enter one of the seeds above
This can also be done on the seed finder (if those seeds satisfy search result)
However, it can be avoided by setting the seed finder to output a list.

## Stacktrace
Wand.ts:385 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'min')
    at e.value (Wand.ts:385:12)
    at e.value (Wand.ts:310:9)
    at e.value (Wand.ts:744:20)
    at r.value (Shop.ts:233:38)
    at r.value (Shop.ts:285:11)
    at r.value (Shop.ts:324:15)
    at r.value (Shop.ts:308:18)
    at t.<anonymous> (index.ts:128:33)
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)

## Additional Context
I've tried clearing my recent seed searches and clearing all personal data, no effect.

Edit: It occurred to me that i think the issue is that these seeds have wands that have no spells contained, I know sounds weird but they are there.

**Comment by TwoAbove** [comment]
Thanks! I'll release a fix this evening

**Comment by snake0484** [comment]
Thanks, you are the best!

**Comment by TwoAbove** [comment]
@snake0484 Fix is live
