### ISSUE TITLE
Suggestion - Add Dark Cave Layout

### ISSUE THREAD

**Issue by danielniccoli** [TwoAbove/noita-tools#203]
Please add the Dark Cave layout for a seed.

![image](https://user-images.githubusercontent.com/2971735/170685271-2c508168-ffb7-4e2e-b093-428d15a35fd3.png)  
https://noita.fandom.com/wiki/Dark_Cave

**Comment by TwoAbove** [comment]
Thanks! Will take a look as to how difficult this will be

**Comment by TwoAbove** [comment]
Dark cave is now live
