### ISSUE TITLE
BUG - Live Game Helper does not work

### ISSUE THREAD

**Issue by danielniccoli** [TwoAbove/noita-tools#204]
## Describe the bug

Live Game Helper does not work

## To Reproduce
1. Start Screen Capture
2. Capture entire screen.
3. Verify tool is connected
4. Start a new game in Noita.
5. Check back on noitool, no info shown, seed not recognised.

Tested in Firefox and Edge

## Expected behavior
Have the website show the info for the current Noita run.

## Screenshots
![image](https://user-images.githubusercontent.com/2971735/170708728-afd4c0d7-8276-4337-b217-68a3a0b41503.png)

**Comment by TwoAbove** [comment]
Thanks, will take a look this evening

**Comment by TwoAbove** [comment]
@danielniccoli Found the error! Fix should be deployed in the next ~5 mins. v2.19.2
