### ISSUE TITLE
BUG - Fungal Shift Missing Element

### ISSUE THREAD

**Issue by Nicknakin** [TwoAbove/noita-tools#206]
## Describe the bug
Fungal Shifts occasionally show empty spaces where an element should be

## To Reproduce
Search 2727694036 as seed
First fungal shift is _____ to Blood (flask)

## Expected behavior
A material in both spots

## Screenshots

![image](https://user-images.githubusercontent.com/35116791/171299773-1746c721-8897-4077-aa41-be6fc2218832.png)

**Comment by TwoAbove** [comment]
Thanks for the bug report! This is a js number issue - I'll get a fix out in a few hours

**Comment by TwoAbove** [comment]
Update will be out shortly – made it more understandable what's happening in this edge case. Thanks!
