### ISSUE TITLE
BUG - Wrong Perk Lottery

### ISSUE THREAD

**Issue by danielniccoli** [TwoAbove/noita-tools#208]
## Describe the bug

![grafik](https://user-images.githubusercontent.com/2971735/172011312-51b6f993-bacb-4b88-949d-b116d329ca46.png)

In Temple 3 I chose Perk Lottery, but was unable to pick another perk after that. The perk generation is bugged.
Maybe it has something to do with the order, because the perk lottery was on the right spot in-game.

**Comment by TwoAbove** [comment]
Thanks for the bug report! yes, the perk position is meaningful. I'll make a change asap

**Comment by TwoAbove** [comment]
Fix deploying

**Comment by danielniccoli** [comment]
Perk position is still wonky.

Seed: 1715196306
I took the +1 perk and died before reaching the second Holy Mountain, if that makes a difference.

![image](https://user-images.githubusercontent.com/2971735/173202009-a7f16f6b-bb98-4509-b84f-7d85bece8911.png)

![image](https://user-images.githubusercontent.com/2971735/173202014-ec1c3736-59cd-426d-b8b9-329c0802c236.png)

**Comment by danielniccoli** [comment]
Another example.

Seed: 1271636795

![image](https://user-images.githubusercontent.com/2971735/173202572-fc77b93f-492f-4467-90e8-45c61f17ece7.png)



![image](https://user-images.githubusercontent.com/2971735/173202559-95f584f1-009b-4b2e-b240-4e22c17d6493.png)

**Comment by TwoAbove** [comment]
I'll be home in a bit and show what the issue is with re-roll direction

**Comment by TwoAbove** [comment]
Oh, I forgot about this. I'll make a write up tonight

**Comment by TwoAbove** [comment]
So Noita does perk rerolling like so:
```lua

	local perk_spawn_pos = {}
	local perk_count = 0

	-- remove all perk items (also this one!) ------
	local all_perks = EntityGetWithTag( "perk" )
	local x, y
	if ( #all_perks > 0 ) then
		for i,entity_perk in ipairs(all_perks) do
			if entity_perk ~= nil then
				perk_count = perk_count + 1
				x, y = EntityGetTransform( entity_perk )
				table.insert( perk_spawn_pos, { x, y } )

				EntityKill( entity_perk )
			end
		end
	end
```
and then re-generates perks iterating through `perk_spawn_pos`. We are atthe whim of `EntityGetWithTag` returning them in some order. I don't know why they are sometimes out of order. Could it depend on the direction the player is pointing, or some other completely random  logic? I don't know, and reverse-engineering `EntityGetWithTag` Didn't really reveal much after 10-15 minutes

**Comment by danielniccoli** [comment]
So, I found this in the source code:

```lua
 -- this generates global perk spawn order for current world seed
function perk_get_spawn_order( ignore_these_ )
	-- this function should return the same list in the same order no matter when or where during a run it is called.
	-- the expection is that some of the elements in the list can be set to "" to indicate that they're used

	-- 1) Create a Deck from all the perks, add multiple of stackable
	-- 2) Shuffle the Deck
	-- 3) Remove duplicate perks that are too close to each other

	-- NON DETERMISTIC THINGS ARE ALLOWED TO HAPPEN
	-- 4) Go through the perk list and "" the perks we've picked up
        
        ...
```

Maybe that is just the non-deterministic stuff, although I don't believe it, because every time I noticed that the perk locations are incorrect, the middle one was always correct.

**Comment by TwoAbove** [comment]
`perk_get_spawn_order` creates an array that perk generation and perk rerolls get perks from. 
Please note that the rerolls are always correct, just the order is not. 
I'll do some testing with positioning in-game, and maybe I'll get something

**Comment by TwoAbove** [comment]
I made an explainer in the app about the quirks of rerolling, and, unfortunately, that's all we can do right now.
