### ISSUE TITLE
Suggestion - Add config value to always show initial perk lottery chance

### ISSUE THREAD

**Issue by Nicknakin** [TwoAbove/noita-tools#212]
I play noita together and often skip ahead in rerolls to add a perk a friend picked up like perk lottery

**Describe the solution you'd like**
The ability to add a perk as added to my character, ideally under a specific mountain

**Comment by TwoAbove** [comment]
Hey! That's an interesting niche. I'm not sure how to best implement something like that. I'm also weary to go into mods with this tool, since they are some volatile in updates and benefit fewer people. 

I'll think about this one, though!

**Comment by Nicknakin** [comment]
Fair enough, at least a toggle in the settings for "always show perk lottery" would be a great deal of help.

**Comment by TwoAbove** [comment]
That's a great idea! 

I can get that out pretty quickly - it's a few small changes. 

Would you like me to change this suggestion to "show perk lottery"?

**Comment by Nicknakin** [comment]
Sounds great, works for me
