### ISSUE TITLE
Suggestion - Direct link to seed

### ISSUE THREAD

**Issue by danielniccoli** [TwoAbove/noita-tools#215]
I'd like to add noitool.com to my app [noisee](https://github.com/danielniccoli/noisee). To do this, it would be great if I could access any seed by HTTP GET request. Examples

 - https://noitool.com/106752098
 - https://noitool.com/seed/106752098
 - https://noitool.com/?seed=106752098

**Comment by TwoAbove** [comment]
Awesome idea! I wanted to add this for some time, so I'll bump this in prio

**Comment by TwoAbove** [comment]
@danielniccoli Available in v2.21.0!
