### ISSUE TITLE
Suggestion - Better DB error page (Site down - There was an error loading the database: Error: A mutation operation was attempted [...])

### ISSUE THREAD

**Issue by quiddity-wp** [TwoAbove/noita-tools#242]
Tested: https://www.noitool.com/
Tested: https://www.noitool.com/?seed=2111427201
Both:
> There was an error loading the database:
> Error: A mutation operation was attempted on a database that did not allow mutations. InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.

**Comment by TwoAbove** [comment]
Hey! Looks like there was some error with the DB. 

Can you describe how it happened?

Thanks!

If you are okay with just resetting the local db, then do this:
```
    In Chrome, go to Options > Privacy and Security > Cookies and other site data > All cookies and Site Data > Search for Noitool > Click delete
```

**Comment by TwoAbove** [comment]
This can also be caused if you visited the site with Edge with extra security settings (which does not allow local dbs) or in Incognito mode

**Comment by quiddity-wp** [comment]
Oh! Yup, I was loading it in an Incognito window. Solved! 
Sorry for the distraction, and thanks again for the site!

**Comment by TwoAbove** [comment]
It's alright! There should have been an error message about being in an incognito window - I'll double check that it's properly showing. 

What browser are you using? (Ideally a version + OS combo)

**Comment by TwoAbove** [comment]
I'll update that error page to be a bit more informative

**Comment by TwoAbove** [comment]
Updated in https://github.com/TwoAbove/noita-tools/pull/257
