### ISSUE TITLE
Suggestion - Information about fungal shifts

### ISSUE THREAD

**Issue by IljaKosynkin** [TwoAbove/noita-tools#245]
Hey there!
First of all, thanks a lot for the tools you've provided, your work has become my go-to for Noita playthroughs.
While most of the tools there are self-explainotory, I've been struggling to understand how fungal shifts section works.
I would appreciate some documentation on this matter :)

**Comment by TwoAbove** [comment]
Hey! 
My pleasure 😄 

What are you thinking about when you're talking about documentation? A quick primer about how they work in-game or what's displayed?

**Comment by IljaKosynkin** [comment]
Well, basically, I'm not entirely sure what the list of shifts is supposed to represent. It is not all the possible shifts since I've gotten shifts that are not in the list in multiple runs (either one of materials in pair is not present or both of them). 
So what I would like to understand is to how to apply the information in the list to the game.
Maybe I'll give a real world example: normally I'm trying to obtain the flask of lava in either first or second biome and then rush to the fungal caverns to try to shift lava to something harmless (as I would like to get to the power plant biome eventually and it just makes it easier).
So the question would be, how can I utilize the list of shifts to have at least some degree of certainty that I will be able to shift lava (as an example) to something harmless without shifting stuff _to_ lava before? How to read the list exactly?

**Comment by TwoAbove** [comment]
🤔 
Once you encounter situations where the shifts are not correct, can you post them here? This seems like a bug.

The shift table shows, from top to bottom, what fungal shift will happen. The left part shows what will turn into the right part. It should be 100% accurate.

**Comment by IljaKosynkin** [comment]
Yes, sure!
I think I even had the seed somewhere, I'll try to find it.
Another thing that I also was wondering - how does the side on which "Flask" is on affect the shift?

**Comment by TwoAbove** [comment]
The Flask is either on the left or right. Think of it as From and To.
It the Flask is on the left, then, if you hold it during the shift, it will use the flask contents as the From material. If it's on the right, the materials on the left will turn into the flask material

**Comment by IljaKosynkin** [comment]
Ok, so essentially side doesn't matter then?
Like if I have a shift from Lava to Vomit (Flask) and I hold the flask of lava - the shift still will go through and all the lava will be converted to the vomit, right?

Also, found the seed.
So, seed 540760, according to the tool has only two transformations with silver: silver to oil and acid to silver.
I've modified save manually to give me flask with silver and fungus blood, to test out the shift. Silver is being shifted to vomit, which is not in the list. 
I'm attaching the save file so you can test it out yourself
[save00.zip](https://github.com/TwoAbove/noita-tools/files/9709011/save00.zip)

The only specific thing to this save is that I've reset the game before it, not sure if it plays any role. Let me know if you can reproduce the behavior and if it is indeed a bug and not me just not understanding something.

**Comment by TwoAbove** [comment]
In your example, if there's a table like:
```
From  | To
-----------
Lava  | Vomit 
      | (flask)
------------
...
```
And you hold a Lava flask, then Lava will turn into Lava, since it's Lava -> Flask if you hold it.

For the seed,
here's what I see:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/9610438/193883696-e37bd43c-06df-4b4c-a89d-9c01a36c4d92.png">
You go from top to bottom:
First shift will be Flask, water, brine, and chilly water to vomit.
Since you are holding the silver flask, the shift becomes Flast -> vomit. 

The next fungal shift will be Acid -> Flask or Toxic Sludge. If you hold a flask, it will be Acid -> Flask. If not, Acid -> Toxic Sludge

**Comment by IljaKosynkin** [comment]
Ah, so basically flask kind of "overrides" material on the side it is marked at, am I correct?

**Comment by TwoAbove** [comment]
Yes! That's how it works in-game

**Comment by IljaKosynkin** [comment]
Ok I think I understand now
However, circling back to my original comment: is this explained anywhere?
If you google "Noita fungal shift" you most likely will get [this wiki article](https://noita.fandom.com/wiki/Fungal_Reality_Shift) as the top result.
And this article does not seem to be correct, as it implies that shifting materials are determined only at the time of shifting and there is no mention that shifts are "hardcoded" for the seed.
I would suggest adding some sort of explanation to the fungal shifts section itself, as it can be incredibly hard and confusing to figure it out by yourself (depending on seed you're testing on) IMO.

**Comment by TwoAbove** [comment]
Thanks for the feedback, I'll add it in the next release!

**Comment by IljaKosynkin** [comment]
Cool thanks!
As a side note, I do not believe the wiki article is correct. For example it states: "If the player is holding a flask in their hand when the shift occurs, there is a 75% chance that one of the materials in the shift will be the main material in the flask, if any"
But if I understood it correctly there is no "75%", it is "100%" i.e. all the time (for the shifts that react to flask at all). I guess it might feel random because not all the shifts react on flask you're holding, but it actually isn't.
Now maybe I'm misreading, it is kind of late for me, but the wiki article do not seem to align with what we have been discussing so far, this is why I suggested adding docs to the tool itself :)
I think it also would be nice to update the article to make the mechanism more clear, but I personally come to distrust wikies over the years, so it isn't such big of a deal for me :D

**Comment by TwoAbove** [comment]
The 75% is in total, without inner knowledge of how things work.

If you do, it works 100% of the time, 75% of the time

**Comment by IljaKosynkin** [comment]
Ye that is what I meant by "I guess it might feel random because not all the shifts react on flask you're holding".
In any case, isn't wiki supposed to tell you the "inner knowledge" though?
IMO, this article confused me much more, than enlightened.
In any case, I think it might be not the best place to discuss wherever the article is correct or not (unless you're the author of course) 
Thanks again for the explanation, feel free to close down the issue if you do not need it as reminder for the next release :)

**Comment by TwoAbove** [comment]
My pleasure! 

I'll leave this open as an enhancement ticket, so I can track what needs to be done.
I can't promise timelines as to when I'll have the time to add the clarification, though.

**Comment by TwoAbove** [comment]
Updated in https://github.com/TwoAbove/noita-tools/pull/257
