### ISSUE TITLE
BUG - Tool shows incorrect starting potion

### ISSUE THREAD

**Issue by IljaKosynkin** [TwoAbove/noita-tools#246]
## Describe the bug
On some seeds starting potion is reported incorrectly.

## To Reproduce
1. Start seed 2386411 (I use [this ](https://gist.github.com/vexx32/fb3131b740af1602c7eed974ea8d2e46) PowerShell script on vanilla Noita without any mods on).
2. Put the seed in the tool
3. The tool reports that you should start with acid flask, but in the game you start with water flask (not that I'm complaining about it :D)

## Expected behavior
The tool should report the starting flask correctly (as in the game).

## Screenshots
![image](https://user-images.githubusercontent.com/6876788/194781233-99548353-1cc1-439e-b15d-da404cfe08dd.png)
![image](https://user-images.githubusercontent.com/6876788/194781247-c16ddc54-01dd-4e33-8a92-1b3ffd5a0d63.png)
![image](https://user-images.githubusercontent.com/6876788/194781263-19b179c0-82b1-4e4c-ba56-bef5300fa6b3.png)

## Additional context
Generally I've noticed that it happens with "smaller" seed numbers and the flask is always is the water one. Not sure if it is relevant, but my spidey senses telling me that there might be some sort of hardcoded thingy from Noita devs. 
Not that this bug is super-critical, but I feel like anything should be reported and then you might pick it up if it's trivial to fix :)

## Seed list
* 2386411 - incorrect flask
* 4384451 - incorrect second spell
* 4539667 - incorrect first spell

**Comment by TwoAbove** [comment]
Thanks! 

I'll check it out soon. Wonder why this is

**Comment by IljaKosynkin** [comment]
Ah one additional point I've missed, I usually reset the game when doing runs (just a little quirk of mine). 
Btw, is one seed enough or you would like me adding seeds occasionally?

As for the reason, it really seems like something hardcoded in the game. If both ends were random I could suspect just some bug in the code of the tool, but the actual flask always being water seems suspicious to me.

**Comment by TwoAbove** [comment]
I think this is enough! Will take some time to get to this, but I'll prioritize bug fixing

**Comment by IljaKosynkin** [comment]
Hey @TwoAbove. today I've also noticed that along with flask starting spell is also sometimes reported incorrectly. Would you like me to add the seed here or create a new issue for this?

**Comment by IljaKosynkin** [comment]
Yes to what exactly? :)

**Comment by TwoAbove** [comment]
To add the seeds here. I'll investigate everything together

**Comment by TwoAbove** [comment]
To add the seeds here. I'll investigate everything together

**Comment by IljaKosynkin** [comment]
Ok!
Added a section with seeds I've found so far to the original message
Also, I've found a pattern: it seems like the starting loadout is always spark bolt, bombs and flask of water.
I wonder if it might something to do with spells/flasks not being unlocked when you reset.

**Comment by IljaKosynkin** [comment]
Hey @TwoAbove!
I can confirm that this behavior is due to resets. I have started the same seed after completing it and the loadout was the same as in the tool (while being different in the first run). Now, I don't think completion is necessary, however not sure at what point game considers the spell "unlocked" to use. 
The progress tracking system is kind of weird to be honest IMO.
