### ISSUE TITLE
Suggestion - Optional auto-select of the current Daily Run seed?

### ISSUE THREAD

**Issue by ZStoner** [TwoAbove/noita-tools#265]
I don't know if it's possible to compute what the current Daily Run seed is.
I know they reset daily at Midnight UTC.

If it is possible, then likely the **Seed Info** tab would be the place for a checkbox.

Also _(optional)_, to recall a list of the last 5 or so days of Daily Seeds... in case they missed it.

**Comment by TwoAbove** [comment]
Hm, that's an interesting idea! I'll see what I can do

**Comment by TwoAbove** [comment]
@ZStoner Will be out with v2.26.0 https://github.com/TwoAbove/noita-tools/pull/285
