### ISSUE TITLE
Suggestion - A spells and perk pool type of search (for a faster search)

### ISSUE THREAD

**Issue by alch3myst** [TwoAbove/noita-tools#269]
The idea is to create a pool of spells and perks, and search for each of them in all levels, not in specific levels, its a simple implementation with a huge payoff.

#### A example:
Search for a seed with circle of vigor, luminous drill, ping pong, add mana, tinker with wands, no more shuffle, exploding corpse
That will take like 50 hours of search in the current search method, or a long and tedious to build and/or statements on filters, but if we search for this in any level and any order, the search will be much more, and the gameplay more challenging and natural (will not feel as much as a set seed)

And you can even add a point system to this search, like, each time the script finds a one of the things in the pool, we add a score point, then we can make a threshold to show the seed, in the example above we will have 7 spells/perks so 7 points, and we can chose to show seeds with 80% of the points as a requirement, and make the search even faster.

**Comment by TwoAbove** [comment]
Thanks for the great idea! 

I now have so many cool things that can be added to the tool that I think it's time for me to make an epic for seed search improvements.

**Comment by TwoAbove** [comment]
@alch3myst Will be out with v2.26.0 https://github.com/TwoAbove/noita-tools/pull/285
