### ISSUE TITLE
BUG - Pacifist chests are incorrect >27 PWs out

### ISSUE THREAD

**Issue by pudy248** [TwoAbove/noita-tools#270]
Noita gets chest RNG from PositionSeedComponent, which rounds numbers to 6 decimal significant figures. This means that numbers >1 million are rounded to the 10s place, >10 million are rounded to the 100s place, and so on. Adding rounding to x positions at those increments should probably be sufficient to fix this bug.

**Comment by pudy248** [comment]
It would appear that chests are the only entities which implement PositionSeedComponent, so no other changes are needed to other parts of the calculation.

**Comment by TwoAbove** [comment]
huh, that's super interesting! Thanks for the bug!

**Comment by TwoAbove** [comment]
@pudy248 do you know what rounding is used for this? Regular or half_even or half_odd?

**Comment by pudy248** [comment]
I used regular rounding, which worked before the patch. It seems broken now though, I'll investigate more closely tomorrow morning.

**Comment by TwoAbove** [comment]
Looks like it's regular rounding :thinking: I got the correct result with it and pacifist chests during testing

**Comment by TwoAbove** [comment]
Forgot to close these
