### ISSUE TITLE
BUG - Another noita update broke stuff

### ISSUE THREAD

**Issue by pudy248** [TwoAbove/noita-tools#272]
This time it changed the way floats are rounded to ints for display purposes. This makes wand capacities frequently off by one, since they're kept as floats during generation for a while. I haven't figured out what exactly the game does now, but it looks like a round was changed to a floor or something similar. Basically, wands who's float capacities' float representations are >0.5 will have capacity 1 lower in the game than in Noitool.

**Comment by TwoAbove** [comment]
Thanks, I'll do another check and update the dev branch soon. I suspect that it's round half-even

**Comment by TwoAbove** [comment]
Much more than that got changed

**Comment by TwoAbove** [comment]
max_uses was updated
