### ISSUE TITLE
BUG - Seed finder does not max out CPU

### ISSUE THREAD

**Issue by tommitytom** [TwoAbove/noita-tools#277]
I didn't really want to add this as a bug, since it's not really a showstopper, but it appears that the seed finder does not max out CPU cores that it is searching on.  It only seems to use 25% of my overall CPU resources: 

![image](https://user-images.githubusercontent.com/1239670/226151814-31572871-f2c3-4384-9c13-50acfa6c842c.png)

The cr4xy.dev one seems to be able to max out all my CPU cores.  I've not delved in to the code to have a look, but is this done on purpose to make sure the computer its run on remains responsive?

**Comment by TwoAbove** [comment]
Thanks! There's an update coming that should fix this.

**Comment by TwoAbove** [comment]
Just to confirm, you're using multithreading, right?

**Comment by tommitytom** [comment]
Yep!

**Comment by tommitytom** [comment]
Legend, thanks mate!
