### ISSUE TITLE
BUG - Pacifist chest wand spawns are wrong (sometimes?)

### ISSUE THREAD

**Issue by pudy248** [TwoAbove/noita-tools#281]
998125 for an example seed

Likely a case of the offset added in the last update not being applied to the wand seed coordinates correctly. I had a similar bug in my code, it's most likely due to the chest RNG using a decimal offset, but the wand gen uses an integer-rounded version of the offset. Here's what my code looks like for the relevant sections: 

Chest coordinate implementation: `random.SetRandomSeed(roundRNGPos(x) + 509.7, y + 683.1);`
Wand coordinate implementation: 
`//s is the chest itself`
`int rand_x = s.x;`
`int rand_y = s.y;`
`if (s.sType == TYPE_CHEST) {`
`	rand_x += 510;`
`	rand_y += 683;`
`}`
`random.SetRandomSeed(rand_x, rand_y)`

**Comment by TwoAbove** [comment]
Thanks! I'll take a look and post a fix asap

**Comment by TwoAbove** [comment]
Fixed in https://github.com/TwoAbove/noita-tools/pull/283
