### ISSUE TITLE
Cuda integration?

### ISSUE THREAD

**Issue by Lucozade1852** [TwoAbove/noita-tools#305]
Is it even possible to integrate cuda into this? I feel like if it works it may greatly increase performance.

**Comment by TwoAbove** [comment]
Hey! 
In the browser, that's not yet possible. There are things in the works with [webgpu](https://caniuse.com/webgpu) and [compute shaders](https://developer.chrome.com/articles/gpu-compute/), all in very early stages, but I'm tracking progress and will definitely try integrating it once it's more capable! A good step toward using those would be to move all the searchers to c++ WASM, and I'm in the middle of doing that when I have free time. That alone will make searches faster. 

If you are interested in CUDA, `pudy248` on Noita's discord has been working on a CUDA seed searcher, and your intuition is correct, it's pretty fast!
