### ISSUE TITLE
BUG - Blood Rain breaks page

### ISSUE THREAD

**Issue by Boneful** [TwoAbove/noita-tools#307]
## Describe the bug

Loading a seed with blood rain breaks the page, fixed by refreshing. Makes viewing such seeds impossible

## To Reproduce

1. Go to Seed Info
2. Enter Seed with Blood Rain (Example: 213235)
3. Attempt to View Seed

## Expected behavior

A normal, detailed view of desired seed

## Screenshots

(Before & After)
![Screenshot 2023-07-13 at 01-34-10 Noitool](https://github.com/TwoAbove/noita-tools/assets/55305072/782fa2a9-ca83-4f39-8449-b94bbf262937)
![Screenshot 2023-07-13 at 01-34-16 Noitool](https://github.com/TwoAbove/noita-tools/assets/55305072/56be6f39-03c0-4e3f-bde9-8dbd56d6d7be)

**Comment by TwoAbove** [comment]
Thanks! I'll get a fix out ASAP

**Comment by TwoAbove** [comment]
Should be fixed soon :+1:
