### ISSUE TITLE
BUG - Nested Gamble Doesn't Register Properly Register

### ISSUE THREAD

**Issue by CalebRenshaw** [TwoAbove/noita-tools#314]
## Describe the bug

If a perk deck has two copies of 'Gamble', it is sometimes possible for one Gamble perk to grab the other. In such an instance, the 2nd layer Gamble will be ignored, and the next two perks instead will be picked. The search tool will show the first Gamble grabbing the 2nd Gamble and one other perk. It should show it grabbing two other perks.

## To Reproduce

1. Example seed: 711801629
2. Re-roll twice by the 2nd Holy Mountain, take Gamble.
3. Gamble and Cordyceps from 3rd Holy Mountain will be grabbed, but not the Fire Immunity.
4. This results in all further perks being one off from actual gameplay.

## Expected behavior

Expected that the first gamble will pick (Gamble -- ignored), Cordyceps, and Fire Immunity, not Gamble and Cordyceps.

## Screenshots

![image](https://github.com/TwoAbove/noita-tools/assets/31461540/9eaca9c9-09d9-42f0-97ee-9d9daee9d1aa)
![image](https://github.com/TwoAbove/noita-tools/assets/31461540/c742a418-16a8-4f35-b1c2-be932f6f4c51)

**Comment by TwoAbove** [comment]
Thanks @CalebRenshaw!

So what will happen is the gamble perk will just be skipped, right?

**Comment by CalebRenshaw** [comment]
Yes, the 2nd gamble perk is ignored entirely.

**Comment by TwoAbove** [comment]
@CalebRenshaw Will be deployed soon

**Comment by TwoAbove** [comment]
@CalebRenshaw Fix is live on www.noitool.com !

**Comment by CalebRenshaw** [comment]
Whoo! Looks great. Thanks for all you do!
