### ISSUE TITLE
BUG - "start from seed" seems to not work

### ISSUE THREAD

**Issue by kingrodriguez** [TwoAbove/noita-tools#330]
## Describe the bug

When entering a number in "Start search from seed: ", the search starts at seed 1 (100 first shown value)

## To Reproduce

 Seeds checked: 100 / 2.147.483.648 (Estimated time left: 162 hours, 29 minutes, 3670.3 avg seeds/s)

## Expected behavior

start the search with the entered seed

## Additional context

- Firefox 121.0.1 (64-bit) / Windows 11

**Comment by TwoAbove** [comment]
Hey @kingrodriguez Sorry for the slow response. I'm currently tied up on time to fix this bug, but I've identified where it is, so I'll be able to fix it as soon as I have time.

Thanks!

**Comment by TwoAbove** [comment]
In the new build this should be fixed
