### ISSUE TITLE
BUG - Beta update changed shifts. 

### ISSUE THREAD

**Issue by derram** [TwoAbove/noita-tools#331]
The beta update that added the ability to use Pouches to affect shifts changed something about shifts. 

As far as I can tell the site is still getting the initial material correct, but the outcome is now different.

**Comment by TwoAbove** [comment]
Hi @derram! Just to double check, you're using [dev.noitool.com](https://dev.noitool.com/info), right?

**Comment by derram** [comment]
Ah, I was using the main site, didn't know about the other. 

Never mind me, then.
