### ISSUE TITLE
BUG - shift's from material missing

### ISSUE THREAD

**Issue by maxsupermanhd** [TwoAbove/noita-tools#350]
## Describe the bug

![image](https://github.com/TwoAbove/noita-tools/assets/20772987/22728df7-b66f-45c6-8679-2257684a6fbf)

## To Reproduce

1289679183

## Additional context

Am I clueless and it is normal or a bug?

**Comment by TwoAbove** [comment]
Thanks! I'll take a look. Most likely this is Diamond -> Diamond. It shouldn't look like this

**Comment by TwoAbove** [comment]
@maxsupermanhd sorry for the long turnaround time for this - I was on a work trip. 

It was Diamond -> Diamond. I've updated the code to show this correctly. Thanks for the bug report!
