### ISSUE TITLE
Design to improve reading clarity of fungal shifts (regarding Held Material)

### ISSUE THREAD

**Issue by five-over-four** [TwoAbove/noita-tools#355]
I have a design suggestion for the fungal shift section. Currently, "Held Material" is shown in bold, and to me, at a first glance, looks like a _title_ to each section rather than just another material like the others. I've made a crude mock-up, showing what I would consider a little more readable to a first-time user:

![Design_idea](https://github.com/TwoAbove/noita-tools/assets/73562879/f3d86554-e754-4e9e-b419-33a1625e3450)

Here, (icon subject to change of course), the Held Material is indicated in the same manner as the regular materials, but with a question mark to show that it's not predetermined. Could be an "X" or something, but the important thing is that the reader immediately understands that the material held is of the same type as the others. Maybe a flask icon would work quite well? Flask with a question mark like this (again, quick mock-up): 

![flask](https://github.com/TwoAbove/noita-tools/assets/73562879/12d809c8-8461-4f6a-8b91-94246f44e8fd)

In either case, I believe it'd be a lot easier to understand the flow of the chart with matching icons and a consistent styling of typography. Thank you for reading.

**Comment by TwoAbove** [comment]
Hey!

I really like this suggestion, and I agree that it's much more readable and understandable. I'll see what I can do to implement this, since it's so much better!

**Comment by TwoAbove** [comment]
I got a cool solution on the beta branch. Check it out! I think this should work well. https://dev.noitool.com/info

**Comment by five-over-four** [comment]
> I got a cool solution on the beta branch. Check it out! I think this should work well. https://dev.noitool.com/info

I don't yet see a change on there- maybe it takes a little while to build? I did manage to find your question mark symbol in base64 in the new commits though, lol.

**Comment by five-over-four** [comment]
> I got a cool solution on the beta branch. Check it out! I think this should work well. https://dev.noitool.com/info

I don't see a change yet on there, but I do see a bunch of changes on the meditation cube, hourglass, and fungal shift stuff in the new commit. Maybe it takes a while to build?

**Comment by TwoAbove** [comment]
No, something's not working with the CI/CD pipeline, thanks for pointing that out

**Comment by TwoAbove** [comment]
@five-over-four Fixed it

**Comment by five-over-four** [comment]
Oh, nice, I see it now. Btw, in the right column, the '?' icon collides vertically a bit with the other icons; you might need a small 'margin-bottom' of about 2px (I tested quickly with that) or whatever the method it is you keep the others apart. Super minor nitpick, looks great otherwise!

**Comment by TwoAbove** [comment]
Thanks, good catch! 

Updated the styling. I like how it turned out. How does it look from your perspective?

**Comment by five-over-four** [comment]
Lot better, very readable. The light mode background for the square might blend in a little too much against the darker gray, but that's up to taste. If you _really_ want nitpicking, you could tweak some of the general vertical alignments for increased symmetry, but it's really not necessary in my opinion, just something I noticed a little:

![alignments](https://github.com/TwoAbove/noita-tools/assets/73562879/6e19d252-3dce-4252-bf18-c67d0e9d4161)

**Comment by TwoAbove** [comment]
This was how it was some time ago — before the new gold/divine ground mechanic, they were aligned. Now, there need to be sub-shifts like this displayed, so it's not aligned. I do like it when it's more aligned, so I'll play around with a couple of options and see if I can make this workable

**Comment by TwoAbove** [comment]
Okay, I'd have to really refactor the design of the shifts, so this will go as a backburner
