### ISSUE TITLE
BUG -Blank page for any seed

### ISSUE THREAD

**Issue by danielniccoli** [TwoAbove/noita-tools#359]
Once you select any seed, the page goes blank.

**Comment by TwoAbove** [comment]
Hey! Thanks for the bug report. I can't seem to get that. Can you please open the dev console (F12) and screenshot any errors that you see? 
Thanks!

**Comment by danielniccoli** [comment]
![image](https://github.com/TwoAbove/noita-tools/assets/2971735/7f52e8f4-f7ce-4d0d-a62f-a1ebea1b2007)

**Comment by TwoAbove** [comment]
Thanks. Can you please try to refresh with control+shift+r (mac command+shift+r) to reload without the cache?

Also, what's your browser+os combo?

**Comment by danielniccoli** [comment]
Cache is already disabled with devtools open. Windows 11, latest Firefox.

**Comment by TwoAbove** [comment]
Thanks. 

I'll try a couple of things to solve this:
1. I'll clear cache on the server to hopefully fix the map data loading 
2. If that doesn't work, I'll make the data get more fault tolerant (so if one info provider fails, like here, it'll still show the rest)

**Comment by danielniccoli** [comment]
Yesterday, it was working again.

Today: "no healthy upstream"

**Comment by TwoAbove** [comment]
Cool, so that means that things should be working now!

**Comment by danielniccoli** [comment]
It does, thanks.
