### ISSUE TITLE
BUG - Perk lotterys taken through a gamble are ignored when calculating affected perks.

### ISSUE THREAD

**Issue by flixalix06** [TwoAbove/noita-tools#372]
## Describe the bug

When perk lottery is taken through a gamble perk, the app does not take it into account when calculating which perks are affected by perk lottery. If perk lottery is taken multiple times, only the instances taken through the gamble perk are ignored. Applies in normal and advanced mode. Applies when lottery preview setting is on if perk lottery is taken multiple times.

## To Reproduce

1. Find a seed where the gamble perk would give perk lottery.
2. Select the gamble perk to be taken.
3. Perks affected by perk lottery will not be indicated.
4. Taking the perk lottery perk normally will indicate which perks would be affected.

## Expected behavior

For taking perk lottery through the gamble perk to cause the app to display which perks will be affected by perk lottery.

## Screenshots

![image](https://github.com/user-attachments/assets/0e0336e2-566c-440b-992a-a46012799e8c)
![image](https://github.com/user-attachments/assets/5f7bfb0f-584a-4803-b4e9-20aa191eeadd)

**Comment by TwoAbove** [comment]
Thanks for the bug report! I remember fixing something similar, so this shouldn't take long

**Comment by TwoAbove** [comment]
Thanks, this will be deployed within the hour
