### ISSUE TITLE
BUG - (Saved) searches do not work properly when editing

### ISSUE THREAD

**Issue by Emilgardis** [TwoAbove/noita-tools#374]
## Describe the bug

When switching between searches, or importing a new search from a string (and sometimes when just editing the same search) the editor starts to switch between the old and new states constantly, eventually settling on one of the states.

## To Reproduce

1. Go to https://www.noitool.com/search
2. Add some rule
3. Click on 'Manage saved searches' and select another saved search, or edit the current search

## Expected behavior

State is updated properly

## Screenshots

https://github.com/user-attachments/assets/8cf88d27-5b32-4a6e-8a40-1c4fc60b03eb

## Additional context

Can reproduce this on Firefox 130.0a1 and Edge 128.0.2739.9

**Comment by Emilgardis** [comment]
should add that I can replicate this on the dev/beta site

**Comment by TwoAbove** [comment]
Oh no, thanks for the report! I'll see what I can do to fix this

**Comment by TwoAbove** [comment]
@Emilgardis This will be deployed soon after I get a couple of other fixes done

**Comment by TwoAbove** [comment]
But definitely in the next several hours
