### ISSUE TITLE
BUG - Energy Shield Selector Shop Search Returning Electric Torch

### ISSUE THREAD

**Issue by rhizomefriend** [TwoAbove/noita-tools#402]
Hi,

As the title says, when I search for energy shield selector in the shop at the first holy mountain, there is always an electric torch in its place.

Can anyone recreate this?

![Screenshot 2024-12-29 024452](https://github.com/user-attachments/assets/3b8f1075-9ae7-45b7-bfd6-d9f4aaceb6e9)
![Screenshot 2024-12-29 024452](https://github.com/user-attachments/assets/9b45c441-59dd-429a-8e36-f297ef70f379)
![Screenshot 2024-12-29 024403](https://github.com/user-attachments/assets/6660bd6b-bb41-4d6f-81e1-2bfdf04de8e3)

**Comment by TwoAbove** [comment]
Thanks! 

Quick question - have you updated the the flags in the settings, and are they up to date with your game?

**Comment by rhizomefriend** [comment]
Solved!
