### ISSUE TITLE
Suggestion: Support for Gamble Perk

### ISSUE THREAD

**Issue by LDSkinny** [TwoAbove/noita-tools#59]
Hi, great tool, I've been using it a lot lately. Would it be possible to get support for recalculating the perks in holy mounts when you take the Gamble perk similar to how it does so for Extra Perk? To clarify, taking the Gamble perk gives you the first two perks from the next Holy Mountain, so if you intend to get this perk on a run, an end user has to mentally shift all future perks over two slots in your tool. It would be nice if clicking the Gamble perk in the interface would do this automatically.

**Comment by TwoAbove** [comment]
Hey! I'll need to check the Noita code to see if gamble and lottery depend on the seed or if it is real random on pickup.

**Comment by TwoAbove** [comment]
I noticed that perk positions in a level are not always 100% as the tool says, so there might be inconsistencies

**Comment by LDSkinny** [comment]
Initially I read on the wiki that it gives the next two perks, so I went and did a test run on a seed where Gamble was in the first Holy Mountain. I did verify that it gave me the two perks that would have been in the next mountain, and the two missing slots were populated by the next one and so on.

From what I understand, the perks in the mountain are like a deck of cards, and arriving in a new one essentially draws three (or more with Extra Perk perks) off the top of the deck (with rerolls being a separate deck entirely), so in theory if you take a wide enough berth around a mountain to avoid loading it, you can cause the perks to spawn out of their normal order, but either way, whenever a perk is spawned it's just pulling off the top of the deck, Gamble included.

**Comment by TwoAbove** [comment]
I moved this to ideas here 
https://github.com/TwoAbove/noita-tools/discussions/73

**Comment by TwoAbove** [comment]
@LDSkinny feature is in dev, will be live this evening! 

If you want to check it out, go to https://noita-tools-dev.herokuapp.com/
