### ISSUE TITLE
Can't reroll in west's worlds

### ISSUE THREAD

**Issue by RealFoxes** [TwoAbove/noita-tools#60]
Can't reroll in west's worlds more than 1
And another issues i can't understand what is it  
![image](https://user-images.githubusercontent.com/45780938/144388775-292e08bc-e812-4e6f-995c-9e676db8940f.png)
It would be cool if we added a title

**Comment by TwoAbove** [comment]
Hey! Thanks, I'll check west and east worlds

This is the fungal shifts table. You either shift flask or the materials. 

Also, what title are you talking about?

**Comment by TwoAbove** [comment]
@RealFoxes Should be fixed in the new version 2.5.0!

**Comment by RealFoxes** [comment]
> Hey! Thanks, I'll check west and east worlds
> 
> This is the fungal shifts table. You either shift flask or the materials.
> 
> Also, what title are you talking about?

I mean need add title to this table
