### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by KolumbusFreund** [TwoAbove/noita-tools#65]
I think it would help if you could see the wands and spells found in the holly mountains

**Comment by TwoAbove** [comment]
Hey! @KolumbusFreund 

Unfortunately, that's not possible right now because the function to get the spells and wand configs are in the engine and I'll need to decompile it to find out how they work

**Comment by TwoAbove** [comment]
I moved this to ideas here 
https://github.com/TwoAbove/noita-tools/discussions/73
