### ISSUE TITLE
Support for other modes?

### ISSUE THREAD

**Issue by EBTheHero** [TwoAbove/noita-tools#66]
Nightmare mode is surprisingly more luck dependant and a tool like that would help a lot!

Would it be a lot of work to implement support for it?

**Comment by TwoAbove** [comment]
Hi @EBTheHero !

The short answer is I don't know, I'll have to check. 

The long answer is my current priority is finishing all of the seed search tabs, do some internal refactoring, and see what other useful information I can get from the game. Also I want to add some qol updates to the UX before I delve into something large as nightmare.

I'll keep you posted on when I'll start working on nightmare.

**Comment by EBTheHero** [comment]
You go man!

**Comment by TwoAbove** [comment]
I moved this to ideas here 
https://github.com/TwoAbove/noita-tools/discussions/73
