### ISSUE TITLE
Noita Tools not calculating the correct recipes in Noita Update 15 (December 2020 build)

### ISSUE THREAD

**Issue by Johnyknowhow** [TwoAbove/noita-tools#8]
Not much to write here, other than the recipe calculations must have changed since the last update to this utility (probably on 1.0 launch?), and the recipes generated by the tool on the https://noita-tools.herokuapp.com/ site are no longer accurate. 

I figured I must have been doing something wrong after I managed to gather the ingredients to create Lively Concoction, and nothing was happening, but it had never occurred to me that the calculator was the issue, haha

Neffc's [NARG](https://github.com/Neffc/narg/) is working with the latest version of the game, so if this tool doesn't get fixed, it's not that big a deal, it's just there are lots of links online to the site when searching for 'noita LC calculator', and it tends to be the first result, so others like myself might get confused as to why it's not working anymore.

**Comment by TwoAbove** [comment]
Wow, I didn't know it was popular. 

I'll see what I can do to get it up to date

**Comment by TwoAbove** [comment]
I'll update the description asap to warn people and make a fix

**Comment by TwoAbove** [comment]
@Johnyknowhow I've updated the tool to work with 1.0

**Comment by TwoAbove** [comment]
I appreciate that you pointed this out
