### ISSUE TITLE
Perk lottery feature

### ISSUE THREAD

**Issue by TrabacchinLuigi** [TwoAbove/noita-tools#87]
just noticed that the perk lottery feature break site in west worlds (select the lottery perk an then anything else and the site reloads itself). 
in east ones it doesn't work, won't let you select anything

**Comment by TwoAbove** [comment]
Hm, thanks for letting me know! I'll check it out

**Comment by TwoAbove** [comment]
Can confirm, will deploy a fix in the evening

**Comment by TwoAbove** [comment]
Should be resolved in new version
