### ISSUE TITLE
No update after new game

### ISSUE THREAD

**Issue by twothe** [TwoAbove/noita-tools#90]
Whenever I start a new game after dying, the automatic seed detector will not update. I have to manually stop and restart the screen capture to have it rescan the new seed.

**Comment by twothe** [comment]
Varies, usually over 10 minutes.

**Comment by TwoAbove** [comment]
@twothe I added some extra checks in the OCR code. I hope that fixes it. Should be deployed soon. Don't forget to Ctrl+Shift+R refresh the page to clear any cache
